name: CI/CD Pipeline - Kubernetes Infra

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  update-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Check out infra-k8s repo
        uses: actions/checkout@v2

      - name: Update Kubernetes manifests
        run: |
          find ./k8s -name 'deployment.yaml' -exec sed -i 's|image:.*|image: gabiponcet/lanchonete-app:latest|' {} +
          git diff --exit-code || echo "Changes detected"

      - name: Commit and push changes to infra-k8s repo
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "gabiponcet@gmail.com"
          git config --global user.name "gabiponcet"
          git add .
          git commit -m "Update deployment to latest image - $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --verbose https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/DenisWm/infra-k8s.git HEAD:master